[package]
name = "home_tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swayipc.workspace = true
cursive.workspace = true
anyhow.workspace = true